# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 112f9af7681ca492c0bca9b80a9d3bd85de850f6448b8cc81def771f60bb0d58868d750473a58a4a94dde6b585a462ae8df2de23d635cd769fc2c0e4828ea6c6

test:
  secret_key_base: 93a36a0cbc071c318d9359b64b80b9e1b02182f390369defde0b4a3d939e4af9e6e7c60df246ceb4f44445f142aeb1d757c57378a6fc092d60435f8f7159564a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
